---
title: "ateia"
description: "WSI processing nf-core-style pipeline: preprocessing, registration, segmentation, quantification, and phenotyping."
version: "0.1.0"
authors:
  - name: "ateia team"
    email: "devnull@example.org"
license: "MIT"
keywords:
  - nextflow
  - nf-core
  - wsi
  - pathology
tags:
  - microscopy
  - imaging
  - seg
homepage: "https://example.org/ateia"
ci: .github/workflows/ci.yml
docs_url: docs
inputs:
  - name: input
    type: glob
    description: "Glob for input image files, e.g. './data/*.nd2'"
outputs:
  - name: merged
    description: "Merged WSI produced by registration (merged/merged_all.ome.tif)"
  - name: segmentation
    description: "Segmentation mask (segmentation/*_segmentation.tif)"
  - name: quant
    description: "Quantification CSV (quant/merged_quant.csv)"
  - name: pheno
    description: "Phenotyping CSV (pheno/merged_pheno.csv)"
